INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (5, '4-7-8 Breathing', 'Inhale for 4 seconds, hold for 7 seconds, and exhale for 8 seconds. Repeat 4 times to reduce stress and anxiety.', 1, 76, 'breathing', NULL, '["Inhale for 4 seconds", "Hold for 7 seconds", "Exhale for 8 seconds"]');
INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (6, 'Body Scan Meditatio', 'Bring your attention through your body, starting from your toes and moving up to your head. Notice each sensation without judgment.', 2, 30, 'audio', NULL, '["toes", "legs", "chest", "arms", "fingers", "head"]');
INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1007, '["Belly Breathing (Diaphragmatic Breathing"]',

Sit or lie in a comfortable place.
Place one hand on your chest and one hand on your abdomen.
The bottom hand should do the moving.
The top hand should remain still.', 1, 60, 'breathing', '', '""Inhale for 4 seconds", "Hold for 2 seconds", "Exhale for 6 seconds""');
INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1008, 'Pursed Lip Breathing', 'Pursed lip breathing slows your breathing pace, making each breath more effective. It also helps you get more oxygen into your lungs.

Inhale slowly through your nose for two seconds with your mouth closed.
Purse (pucker) your lips as though you’re going to whistle.
Exhale slowly and gently through your pursed lips for four or more seconds.', 1, 60, 'breathing', '', '""Inhale for 2 seconds", "Exhale for 4 seconds""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1009, 'Box Breathing', 'Box breathing is a powerful yet simple relaxation technique that can help you reset your breath and restore calm. It is often used by athletes and professionals to reduce stress and improve concentration.

Sit upright in a comfortable chair with your feet flat on the floor.
Inhale slowly through your nose while counting to four.
Hold your breath for a count of four.
Exhale slowly for a count of four.
Hold again for four before repeating.', 1, 60, 'breathing', '', '""Inhale for 4 seconds", "Hold for 4 seconds", "Exhale for 4 seconds", "Hold for 4 seconds""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1010, 'Counting Body Awareness', 'Bring mindful attention to different body parts while gently counting to maintain focus.

Sit or lie comfortably. As you breathe, move awareness through body regions from toes to head. With each area, count slowly and feel the sensations without judgment.', 2, 60, 'meditatio', '', '""toes", "legs", "abdomen", "chest", "shoulders", "head""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1011, 'Five Regions Grounding', 'Ground your attention by connecting with key regions of your body.

Lie or sit still. Slowly shift your focus between five main body zones, starting from the lower part and moving upward. Acknowledge each area with curiosity and care.', 2, 60, 'meditatio', '', '""feet", "legs", "belly", "arms", "head""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1012, 'Tension Release Meditatio', 'A focused scan to detect and release tension held in various body regions.

Bring your attention gently to each part of the body. As you exhale, imagine releasing any tightness or discomfort found in that area.', 2, 90, 'meditatio', '', '""feet", "calves", "thighs", "pelvis", "torso", "neck", "jaw", "forehead""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (1013, 'Gentle Awareness Sweep', 'A soft awareness sweep from the base of the body to the top, cultivating a calm and connected state.

Let attention travel slowly from one region to the next. No need to change anything—just observe and allow presence.', 2, 45, 'meditatio', '', '""toes", "feet", "legs", "abdomen", "chest", "hands", "arms", "face", "head""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (2005, 'Full Body Relaxation in 10 Steps', 'A guided exercise that helps you release tension throughout the body, starting from the feet and moving up to the head.', 3, 120, 'pmr', '', '""Tense your feet muscles, hold for 5 seconds, then relax.", "Tense your calves, hold for 5 seconds, then relax.", "Tense your thighs, hold, then relax.", "Tighten your abdomen, hold, then release.", "Clench your fists, then let .", "Tense your arms and shoulders, hold, then relax.", "Raise your shoulders to your ears, hold, then drop.", "Tighten your neck, hold gently, then relax.", "Squeeze your facial muscles, then relax.", "Take a deep breath in, hold, and exhale slowly.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (2006, 'Express PMR', 'A quick routine, perfect for short breaks at work or before sleep.', 3, 60, 'pmr', '', '""Inhale deeply and clench your fists.", "Hold for 5 seconds, then exhale and let .", "Focus on your breathing and overall relaxation.", "Tense your shoulders briefly, then drop them with an exhale.", "Take a final deep breath and scan your body for any tension.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (2007, 'Shoulders and Neck Release', 'Focuses on releasing stress from your upper body, especially the shoulders and neck.', 3, 120, 'pmr', '', '""Lift your shoulders as close to your ears as possible, hold, then relax.", "Gently tilt your head to the right, hold for 5 seconds, return to center.", "Repeat on the left side.", "Roll your shoulders backwards slowly, then forward.", "Take a deep breath and exhale all remaining tension.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (2008, 'Beginner-Friendly PMR', 'A simple introduction to PMR, ideal for first-timers.', 3, 60, 'pmr', '', '""Gently tense each muscle group, starting from feet to face.", "Avoid over-tightening; focus on awareness.", "Observe the difference between tension and relaxation.", "Breathe deeply after each group is relaxed.", "Finish with a moment of quiet stillness.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (2009, 'PMR with Visualizatio', 'Combines PMR with mental imagery for a deeper relaxation experience.', 3, 300, 'pmr', '', '""Visualize yourself on a calm beach.", "As you tense and relax each muscle group, imagine waves washing away tension.", "Start from your feet and move upward slowly.", "Use your breath to deepen the imagery.", "Conclude with full-body relaxation and peaceful visualization.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (3004, 'Safe Place Visualizatio', 'Visualize a calm, safe space where you feel completely relaxed and protected.', 4, 240, 'visualizatio', '', '""Close your eyes and imagine a peaceful place.", "Focus on the colors, sounds, smells, and textures around you.", "Visualize yourself walking around and feeling safe.", "Take a deep breath and let  of any stress.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (3005, 'Mountain Visualizatio', 'Visualize yourself as a strong, grounded mountain.', 4, 240, 'visualizatio', '', '""Sit comfortably and imagine a mountain.", "Feel your body become tall and still like the mountain.", "Picture yourself withstanding winds and storms.", "Feel your breath anchoring you to the ground.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (3006, 'Cloud Release Visualizatio', 'Visualize your worries floating away on clouds.', 4, 240, 'visualizatio', '', '""Picture a clear sky with slow-moving clouds.", "Imagine placing a worry on each cloud.", "Watch the clouds drift away, taking your stress with them.", "Feel lighter with each breath.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (4004, 'Positive Affirmation Repetitio', 'Repeat empowering statements that reinforce your self-worth.', 5, 120, 'confidence', '', '""Take a deep breath.", "Say out loud: ''I am confident. I am capable. I believe in myself.''", "Repeat this affirmation three times.", "Reflect on how it feels to believe in these words.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (4005, 'Past Success Visualizatio', 'Recall and visualize a moment when you felt proud of yourself.', 5, 100, 'confidence', '', '""Close your eyes and think of a time you accomplished something meaningful.", "Recall what you saw, felt, and heard in that moment.", "Remind yourself: ''That success came from my own effort.''", "Let the feeling of pride and confidence fill you.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (4006, 'Power Pose Practice', 'Use body language to shift your mindset and feel more powerful.', 5, 150, 'confidence', '', '""Stand tall with your hands on your hips, feet shoulder-width apart.", "Hold this pose for 2 minutes, breathing slowly.", "Say to yourself: ''I am strong and ready for anything.''", "Smile gently and continue your day with intention.""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (5009, 'Gratitude Pause', 'Shift focus from stress to appreciation by writing three things you''re grateful for.', 2002, 180, 'stress-management', '', '""Write three things you''re grateful for today.", "What makes each of them meaningful to you?", "How do you feel after reflecting on them?""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (5010, 'Reframe Your Thinking', 'Challenge a stressful thought by writing a more balanced one.', 2002, 240, 'stress-management', '', '""Write down a stressful thought you had today.", "How true is that thought, really?", "Write a more balanced version of that thought.", "How does the new version make you feel?""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (5011, 'Stress Triggers Journal', 'Identify recurring sources of stress and how you usually respond.', 2002, 300, 'stress-management', '', '""List three situations that caused you stress recently.", "How did you react to each one?", "Was your reaction helpful or harmful?", "What would you like to do differently next time?""')
;INSERT INTO "Exercises" ("Id", "Name", "Description", "CategoryId", "Duration", "InteractionType", "MediaUrl", "StepsJson") VALUES (5012, 'Let it out on paper', 'Write down what’s bothering you, what you can control, and what you want to let .', 2002, 300, 'stress-management', '', '""Write about what is stressing you right now.", "What part of this situation is in your control?", "What is one small thing you can do today to feel better?""')
SET IDENTITY_INSERT INTO "Exercises" OFF